// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh2wHJAkUq_jWxa7ei7V3rtqZrZVhVGF8',
    appId: '1:1061922940989:web:0f962638fd0578b5e16254',
    messagingSenderId: '1061922940989',
    projectId: 'auth-580a8',
    authDomain: 'auth-580a8.firebaseapp.com',
    storageBucket: 'auth-580a8.appspot.com',
    measurementId: 'G-HVHCR0M2S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xeOy7U4RMeqd6B0YlnbJDl-_HowpzQs',
    appId: '1:1061922940989:android:ef9bf6e926a0bf63e16254',
    messagingSenderId: '1061922940989',
    projectId: 'auth-580a8',
    storageBucket: 'auth-580a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJCEfeXX-KOhLQZiHJNbfB15fEiJYidk',
    appId: '1:1061922940989:ios:58e447983f1dd6e5e16254',
    messagingSenderId: '1061922940989',
    projectId: 'auth-580a8',
    storageBucket: 'auth-580a8.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJCEfeXX-KOhLQZiHJNbfB15fEiJYidk',
    appId: '1:1061922940989:ios:58e447983f1dd6e5e16254',
    messagingSenderId: '1061922940989',
    projectId: 'auth-580a8',
    storageBucket: 'auth-580a8.appspot.com',
    iosBundleId: 'com.example.auth',
  );
}
